TARGET_SLOT_DURATION = 30 * 60  # 30 min
BUMPER_DURATION = 15  # sec
DEFAULT_BLACK_THRESHOLD = 15
DEFAULT_SAMPLE_INTERVAL = 1.0
DEFAULT_MIN_GAP = 150
DEFAULT_MAX_BREAKS = 4
DEBUG_BUMPER_TEXT = False  # Set to False to run normally

BUMPER_MUSIC_PATH = "/DATA/music.wav"
BUMPER_NTSC_PRESET = "/DATA/Basic VHS.json"